# Generated by Django 5.2.8 on 2025-12-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0003_index_indexprice_alter_eodprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='rsc_sensex_ema10',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='rsc_sensex_ema5',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='rsc_sensex_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
