# Generated by Django 5.2.8 on 2026-01-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0004_parameter_rsc_sensex_ema10_parameter_rsc_sensex_ema5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='rsc_nse_ema10',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='rsc_nse_ema5',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='rsc_nse_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
