# Generated by Django 5.2.8 on 2025-12-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EMA_50', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('EMA_200', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('RSC_20', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('is_successful_trade', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
