# Generated by Django 5.2.8 on 2025-12-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricefeature',
            name='symbol',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
